services:
  instituto-siqueira:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: instituto-siqueira
    restart: always
    networks:
      - root_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.instituto-siqueira.rule=Host(`institutosiqueira.com.br`) || Host(`www.institutosiqueira.com.br`)"
      - "traefik.http.routers.instituto-siqueira.entrypoints=websecure"
      - "traefik.http.routers.instituto-siqueira.tls.certresolver=mytlschallenge"
      - "traefik.http.services.instituto-siqueira.loadbalancer.server.port=80"

networks:
  root_default:
    external: true
